"""Processing endpoints (internal: called only by the CourseCraft API's job worker).

`POST /process/lesson` can take minutes for a long video (notes are generated by a local or
remote LLM). It is a plain synchronous request: the worker waits for it with a long timeout.
"""

from typing import Annotated

from fastapi import APIRouter, Depends, HTTPException, status

from app.api.vectors import get_vector_index, run_infra, unavailable
from app.config import Settings, get_settings
from app.generation.notes import LlmUnavailableError, NotesGenerationError, NotesGenerator
from app.generation.providers import ProviderNotConfiguredError, get_chat_model
from app.generation.usage import UsageTotals
from app.processing.chunking import TimedText
from app.processing.indexing import VectorIndex
from app.processing.lesson import EmptyTranscriptError, LessonProcessor
from app.schemas import (
    ChunkOut,
    NotesOut,
    ProcessLessonRequest,
    ProcessLessonResponse,
    UsageOut,
)

router = APIRouter(prefix="/process", tags=["processing"])


def get_notes_generator(settings: Annotated[Settings, Depends(get_settings)]) -> NotesGenerator:
    """A generator per request, so its token totals cover exactly this lesson."""
    totals = UsageTotals()
    try:
        model = get_chat_model(settings, operation="lesson-notes", totals=totals)
    except ProviderNotConfiguredError as error:
        raise unavailable(str(error)) from error
    return NotesGenerator(
        model,
        model_name=settings.chat_model,
        map_tokens=settings.notes_map_tokens,
        reduce_tokens=settings.notes_reduce_tokens,
        concurrency=settings.llm_concurrency,
        usage=totals,
    )


@router.post("/lesson")
def process_lesson(
    body: ProcessLessonRequest,
    index: Annotated[VectorIndex, Depends(get_vector_index)],
    notes: Annotated[NotesGenerator, Depends(get_notes_generator)],
    settings: Annotated[Settings, Depends(get_settings)],
) -> ProcessLessonResponse:
    """Transcript → chunks + notes, then the chunks are embedded and stored (idempotent).

    422 = empty transcript; 502 = the model's output stayed unusable after 3 attempts;
    503 = the model, embedding service or vector database is unavailable (retry later).
    """
    processor = LessonProcessor(
        index,
        notes,
        chunk_target_tokens=settings.chunk_target_tokens,
        chunk_overlap_tokens=settings.chunk_overlap_tokens,
    )
    try:
        result = run_infra(
            lambda: processor.process(
                course_id=body.course_id,
                lesson_id=body.lesson_id,
                youtube_id=body.youtube_id,
                video_title=body.video_title,
                segments=[TimedText(s.text, s.start, s.duration) for s in body.segments],
            )
        )
    except EmptyTranscriptError as error:
        raise HTTPException(status.HTTP_422_UNPROCESSABLE_CONTENT, str(error)) from error
    except NotesGenerationError as error:
        raise HTTPException(status.HTTP_502_BAD_GATEWAY, str(error)) from error
    except LlmUnavailableError as error:
        raise unavailable(str(error)) from error

    n = result.notes
    return ProcessLessonResponse(
        course_id=body.course_id,
        lesson_id=body.lesson_id,
        chat_model=n.model,
        embedding_model=settings.embed_model,
        chunks=[
            ChunkOut(
                id=chunk_id,
                index=c.index,
                text=c.text,
                start_sec=c.start_sec,
                end_sec=c.end_sec,
                token_count=c.token_count,
                overlap_chars=c.overlap_chars,
            )
            for chunk_id, c in zip(result.chunk_ids, result.chunks, strict=True)
        ],
        notes=NotesOut(
            title=n.title,
            summary=n.summary,
            key_concepts=n.key_concepts,
            notes_markdown=n.notes_markdown,
            reading_time_min=n.reading_time_min,
            anchors=n.anchors,
            prompt_ids=n.prompt_ids,
        ),
        usage=UsageOut(
            llm_calls=result.llm_calls,
            input_tokens=result.tokens.input_tokens,
            output_tokens=result.tokens.output_tokens,
        ),
        elapsed_sec=result.elapsed_sec,
    )
