"""Generates lesson notes for recorded fixture lectures with the configured LLM (manual quality
checks, issue #23). Output: docs/eval/notes-samples/<fixture>.<model>.md

    pnpm ai:notes-sample whisper manual auto     # from the repo root
    uv run python -m scripts.generate_notes whisper   # from services/ai
"""

import re
import sys
import time
from pathlib import Path

from app.config import get_settings
from app.generation.notes import NotesGenerator
from app.generation.providers import get_chat_model
from app.generation.usage import UsageTotals
from app.processing.chunking import TimedText
from tests.fixture_data import VIDEOS, FixtureName, load_transcript, load_videos

OUT = Path(__file__).resolve().parents[3] / "docs" / "eval" / "notes-samples"


def main(names: list[str]) -> None:
    settings = get_settings()
    videos = load_videos()
    for name in names:
        if name not in VIDEOS:
            sys.exit(f"unknown fixture {name!r}; choose from {list(VIDEOS)}")
        fixture: FixtureName = name  # narrowed by the `in VIDEOS` check
        transcript = load_transcript(fixture)
        segments = [TimedText(s.text, s.start, s.duration) for s in transcript.segments]
        video = videos[VIDEOS[fixture]]
        totals = UsageTotals()
        model = get_chat_model(settings, operation="lesson-notes-sample", totals=totals)
        generator = NotesGenerator(
            model,
            model_name=settings.chat_model,
            map_tokens=settings.notes_map_tokens,
            reduce_tokens=settings.notes_reduce_tokens,
            concurrency=settings.llm_concurrency,
        )
        started = time.perf_counter()
        notes = generator.generate(video.title, segments)
        elapsed = time.perf_counter() - started

        covered = segments[-1].start + segments[-1].duration
        slug = re.sub(r"[^a-z0-9]+", "-", settings.chat_model.lower()).strip("-")
        path = OUT / f"{fixture}.{slug}.md"
        path.parent.mkdir(parents=True, exist_ok=True)
        header = "\n".join(
            [
                f"<!-- Generated by scripts/generate_notes.py; fixture '{fixture}' -->",
                f"# Sample: {notes.title}",
                "",
                "| Field | Value |",
                "| --- | --- |",
                f"| Video | `{video.youtube_id}` {video.title} ({video.channel}) |",
                f"| Transcript | {transcript.source}, first {covered / 60:.1f} min, "
                f"{len(segments)} segments |",
                f"| Model | `{settings.llm_provider}` / `{settings.chat_model}` |",
                f"| Prompts | {', '.join(f'`{p}`' for p in notes.prompt_ids)} |",
                f"| Calls / tokens | {totals.calls} calls, {totals.counts.input_tokens} in, "
                f"{totals.counts.output_tokens} out |",
                f"| Time | {elapsed:.0f} s |",
                f"| Summary | {notes.summary} |",
                f"| Key concepts | {', '.join(notes.key_concepts)} |",
                f"| Anchors | {len(notes.anchors)} (all snapped to real caption times) |",
                f"| Reading time | {notes.reading_time_min} min |",
                "",
                "---",
                "",
            ]
        )
        path.write_text(header + notes.notes_markdown, encoding="utf-8")
        print(f"wrote {path} ({elapsed:.0f} s, {totals.calls} calls)")


if __name__ == "__main__":
    main(sys.argv[1:] or ["whisper"])
